### ISSUE TITLE
Add coursier package

### ISSUE THREAD

**Issue by JD557** [avdv/scalals#280]
It would be pretty cool to have scalals in https://github.com/coursier/apps
That would make the installation much easier (just `cs install --contrib scalals`).

You can see https://github.com/coursier/apps/blob/main/apps-contrib/resources/sn-bindgen.json for an example with native binaries.

**Comment by avdv** [comment]
Good call! Does that mean scalals needs to be published to some repository first?

**Comment by JD557** [comment]
That's a good question. I don't know, but [the documentation](https://get-coursier.io/docs/cli-appdescriptors#publish-your-application) does mention "In order for your application to be install-able via install, it should be published to Maven / Ivy repositories.", so I guess that's the case.

**Comment by avdv** [comment]
I am just using jitpack.io to serve the version information needed by coursier and created a PR: https://github.com/coursier/apps/pull/225
